/**
 * Authentication Actions
 *
 */
export const AUTHENTICATION_SAVE = 'AUTHENTICATION_SAVE';
export const AUTHENTICATION_UPDATE = 'AUTHENTICATION_UPDATE';
export const AUTHENTICATION_REMOVE = 'AUTHENTICATION_REMOVE';
